root = "."
tmp_dir = "cache"

[build]
cmd = "go build -o ./dist/app ."
bin = "./dist/app"
full_bin = "APP_ENV=dev APP_USER=air ./dist/app"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]
exclude_dir = ["files", "logs", "dist", "cache"]
delay = 1000 # ms
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true